### ISSUE TITLE
[Issue] Image in white theme doesn't show

### ISSUE THREAD

**Issue by sven-hash** [nymtech/dev-portal#15]
Image are displayed well when using white theme. This [page](https://nymtech.net/developers/integrations/mixnet-integration.html) for example

![](https://i.imgur.com/ddDWmV9.png)

**Comment by mfahampshire** [comment]
Yeah we're going to rework the diagrams and/or add a themed images, which will take a little fiddling :)

**Comment by mfahampshire** [comment]
bear with us on this one, already got a note for it
